- name: "Base Configuration for Ubuntu HomeLab"
  hosts: all
  tasks:

#  - name: Install PackageCloud GPG Key
#    apt_key:
#      url: https://packagecloud.io/gpg.key

  - name: Install Grafana APT Repo
    apt_repository:
      repo: deb https://packagecloud.io/grafana/stable/debian/ jessie main
      state: present

  - name: Enable Oracle Java Repos
    apt_repository:
      repo: ppa:webupd8team/java

  - name: Enable LetsEncrypt/CertBot Repos
    apt_repository:
      repo: ppa:certbot/certbot

  - name: Install OS Packages 
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - ansible
      - vim
      - python3
      - python3-pip
      - python3-tk
      - librtlsdr0
      - net-tools
      - openssh-server
      - htop
      - docker.io
      - vagrant
      - virtualbox
      - grafana
      - syslog-ng
      - vbetool
      - influxdb
      - influxdb-client
      - oracle-java8-installer
      - unifi
      - snmp
      - snmpd
      - snmp-mibs-downloader
      - software-properties-common
      - nginx
      - python-certbot-nginx
      - nmap

  - name: InfluxDB - Telegraf
    apt:
      deb: packages/telegraf_1.5.2-1_amd64.deb 

  - name: Splunk 7.0.2 
    apt:
      deb: packages/splunk-7.0.2-03bbabbd5c0f-linux-2.6-amd64.deb

  - name: Chronograf 
    apt:
      deb: packages/chronograf_1.4.2.1_amd64.deb


  - name: Install Python Packages 
    pip:
      name: "{{ item }}"
      executable: pip3
    with_items:
      - pyrtlsdr
      - amcrest
      - numpy
      - scipy
      - matplotlib
      - boto
      - twilio

  - name: Bash Settings
    copy:
      src: files/ricapar.sh
      dest: /etc/profile.d/ricapar.sh

  - name: Telegraf Base Configuration
    copy:
      src: files/telegraf.conf
      dest: /etc/telegraf/telegraf.conf

  - name: Telegraf Extra Configuration
    copy:
      src: "files/telegraf-{{ item }}.conf"
      dest: "/etc/telegraf/telegraf.d/{{ item }}.conf"
    with_items:
      - outputs
      - osmetrics
      - ubiquiti

  - name: Install Ubiquiti MIBs
    copy:
      src: "snmp/{{ item }}"
      dest: "/usr/share/snmp/mibs/{{ item }}"
    with_items:
      - UBNT-MIB
      - UBNT-UniFi-MIB
      - UBNT-FROGFOOT-RESOURCES-MIB.mib
