---
- name: Add users to group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items:
    - rich
    - erica

- name: Setup Portainer Volume
  docker_volume:
    name: portainer_data

- name: Setup Portainer
  docker_container:
    name: portainer
    image: portainer/portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock 
    ports:
      - "9000:9000"
