---
- name: Install Base Packages
  package:
    name: 
    - ansible
    - vim
    - python3
    - python3-pip
    - python3-tk
    - python3-virtualenv
    - python-pip
    - net-tools
    - openssh-server
    - htop
    - iotop
    - syslog-ng
    - snmp
    - snmpd
    - snmp-mibs-downloader
    - git
    - awscli
    state: latest


- name: Install Python3 Packages 
  pip:
    name:
    - numpy
    - scipy
    - matplotlib
    - boto
    - twilio
    - docker-py
    executable: pip3
